### ISSUE TITLE
Helix themes are not highlighting properly 

### ISSUE THREAD

**Issue by guilhermeprokisch** [Colonial-Dev/inkjet#25]
Hey @Colonial-Dev,
Firstly, thanks for adding the Helix Themes to the project.

However, I noticed that the Helix themes do not include complete keyword definitions that the highlighter uses. When comparing the results of my hardcoded theme with the new Helix theme, the difference is visible. Here is a visual comparison for reference: 

<img width="847" alt="image" src="https://github.com/user-attachments/assets/4e30e2b0-700b-4041-8b42-92658f29b9fa">

I have tested this with Darkcula but observed the same issue across most of the themes I tried out.
It seems that simply reading from the[ toml themes directory](https://github.com/helix-editor/helix/tree/master/runtime/themes) in the Helix repository may result in missing a significant number of keywords for some reason.

Perhaps we need to implement a mapping or redundancy mechanism for the keywords in the highlighter to address this issue.

**Comment by Colonial-Dev** [comment]
Damn, it's not mentioned at all in the (admittedly informal) spec, but it seems like Helix implements fall-through on themes - if `ui.x.y` isn't set but `ui.x` is, it uses `ui.x` :melting_face:

**Comment by Colonial-Dev** [comment]
Not the hardest fix, fortunately - just a post-processing step. Sorry about this - my terminal has been weird w/ `TRUECOLOR` lately, so I just sort of handwaved it away as my problem.

**Comment by guilhermeprokisch** [comment]
@Colonial-Dev, I have drafted a solution using your approach in this [PR](https://github.com/Colonial-Dev/inkjet/pull/26). However, it seems like there is another issue that is preventing the problem from being completely resolved. When comparing the Helix render with inkjet, even after the fallback implementation:

<img width="764" alt="image" src="https://github.com/user-attachments/assets/677c913a-73fd-47d9-b7bd-c736b47998ab">

Upon debugging, I noticed that the `main` and `println`words are now being marked as "variables" by the HighlightEvent, which is why they appear white in the screenshot. This was not the case before version 0.11; at least `println` was marked as `function.macro`. 

It seems that Helix itself should mark `main` as something different in order to render that way, but I am uncertain of what that should be and why Inkjet it's not correctly getting.

**Comment by Colonial-Dev** [comment]
Funny timing! I just implemented my own fix and noticed the same issue. My guess is that the highlighting queries are mixed up; let me try using the ones from the upstream Rust grammar instead of the ones provided by Helix.

**Comment by Colonial-Dev** [comment]
Pasting the sample code here... I'm testing using the Github Dark theme, so having a reference should be helpful.
```rs
fn main() {
    println!("Hello, world!");
    let x = 5;
    let y = 10;
    println!("x + y = {}", x + y);
}
```

**Comment by Colonial-Dev** [comment]
![image](https://github.com/user-attachments/assets/1e354c4a-53c4-4fcb-95e7-b82559c21a2e)
Okay, almost! It's correctly identifying `main` as a function (see the HTML output) but the terminal formatter doesn't seem to get it.

**Comment by Colonial-Dev** [comment]
![image](https://github.com/user-attachments/assets/e8c8a3fc-b0cb-45c3-a512-d1c9d326c648)
Themed HTML formatter gets it right as well, although it seems this theme isn't *quite* faithful to Github (the default text color is gray rather than white)
```rs
fn main() {
    for i in 1..=100 {
        match (i % 3, i % 5) {
            (0, 0) => println!("fizzbuzz"),
            (0, _) => println!("fizz"),
            (_, 0) => println!("buzz"),
            (_, _) => println!("{}", i),
        }
    }
}
```
Maybe this is my terminal color acting up again...?

**Comment by Colonial-Dev** [comment]
Found the issue. Seems like `tree-sitter` doesn't like highlighting line-by-line:
![image](https://github.com/user-attachments/assets/5c6ab964-e5ab-4cf9-b32b-65f8d1de2820)
```rs
// Yes
highlighter.highlight_to_writer(language, &formatter, &source, &mut io::sink());

// No
for line in source.lines() {
    highlighter
        .highlight_to_writer(language, &formatter, line, &mut io::stdout())
        .map_err(|e| io::Error::new(io::ErrorKind::Other, e.to_string()))?;
    println!();
}
 ```

**Comment by guilhermeprokisch** [comment]
Cool!

**Comment by guilhermeprokisch** [comment]
@Colonial-Dev, does this suggest that the Helix grammars are not the most up to date reference to get this from?

If this is the situation for Rust, could it also apply to other languages, right?

**Comment by guilhermeprokisch** [comment]
@Colonial-Dev  also wondering how can helix highlight correctly with a old/wrong  highlighting queries. 


btw the problem still for other languages I tested python and javascript :/

**Comment by Colonial-Dev** [comment]
> @Colonial-Dev also wondering how can helix highlight correctly with a old/wrong highlighting queries.
> 
> btw the problem still for other languages I tested python and javascript :/

Oof, I thought those looked correct... but I don't do a lot of Python and JS. Looks like Python isn't highlighting function calls correctly, but JS looks fine - what're you seeing?

(If you didn't see it already, you can use `cargo test` to generate a sample file called `snippets.html` in the `tests` dir - might be helpful.)

> @Colonial-Dev, does this suggest that the Helix grammars are not the most up to date reference to get this from?
> 
> If this is the situation for Rust, could it also apply to other languages, right?

When I first put together this crate, they were almost universally better than the upstream options (if they even existed) + they didn't rely on custom extensions to the query syntax like Neovim queries do. Since then I've moved ~half of the languages to their upstream queries as things improved or bugs cropped up.

Helix loads the grammars at runtime, and uses a similar system to fetch the source (shelling out to Git + pinning a specific revision). They're *usually* up to date - take Awk, for example - but it could simply be that Helix is still targeting an older version of the grammar for some languages.

(Also, sometimes the parsers and queries are buggy or incomplete, especially for the less-loved languages. Unfortunately there isn't much I can do there.)
